version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-vol:/var/lib/mysql
  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - ../data/redis:/data
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - '8080:80'
    expose:
      - '8080'
    
volumes:
  mysql-vol:
