---
- hosts: all

  vars:
    cent-host: "centos-host"
    ubuntu-host: "ubuntu-host"

  tasks:

    - name: Installing apache
      become: yes
      become_user: root
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Installing httpd
      become: yes
      become_user: root
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Inserting webpage
      become: yes
      become_user: root
      
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Installing webpage
      become: yes
      become_user: root
      
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'



    - name: restart apache
      service: 
        name: apache2 
        state: started 
        enabled: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: restart httpd
      service: 
        name: httpd 
        state: started 
        enabled: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
